In [2]:
import numpy as np
from scipy.stats import levy_stable
from scipy.stats import uniform
from scipy.stats import multivariate_normal

In [4]:
def prior_sample(seed):
    # Sample from prior distribution
    # For univariate alpha-stable models, sample each parameter from its respective uniform distribution
    np.random.seed(seed)
    alpha = uniform.rvs(1.1, 2)  # U[1.1, 2]
    beta = uniform.rvs(-1, 1)  # U[-1, 1]
    gamma = uniform.rvs(0, 300)  # U[0, 300]
    delta = uniform.rvs(-300, 300)  # U[-300, 300]
    return [alpha, beta, gamma, delta]

In [5]:
def univ_alpha_stable_sampler(params,size,seed) :
    alpha,beta,gamma,delta = params[0],params[1],params[2],params[3]
    #print(alpha,beta,gamma,delta)
    y_bar = 0
    np.random.seed(seed)
    w = np.random.standard_exponential(size=size)
    u = np.random.uniform(low = -np.pi/2, high = np.pi/2, size = size)
    if alpha == 1 :
        y_bar = 2/np.pi*((np.pi/2+beta*u)*np.tan(u)-beta*np.log((np.pi/2*w*np.cos(u))/(np.pi/2+beta*u)))
        return gamma*y_bar + delta
    else :
        S = (1+beta**2*np.tan(np.pi*alpha/2)**2)**(1/(2*alpha))
        B = 1/alpha*np.arctan(beta*np.tan(np.pi*alpha/2))
        #print(S,B)
        y_bar = (S*(np.sin(alpha)*(u+B))*(np.cos(u-alpha*(u+B))/w)**((1-alpha)/alpha))/np.cos(u)**(1/alpha)
        return gamma*y_bar + delta

In [6]:
def compute_quantiles(data):
    # Compute quantile-based summary statistics
    quantiles = np.percentile(data, [5, 25, 50, 75, 95])
    v_alpha = (quantiles[4] - quantiles[0]) / (quantiles[3] - quantiles[1])
    v_beta = (quantiles[4] + quantiles[0] - 2 * quantiles[2]) / (quantiles[4] - quantiles[0])
    v_gamma = (quantiles[3] - quantiles[1]) / quantiles[2]
    return v_alpha, v_beta, v_gamma

In [7]:
def S(data):
    # Compute summary statistics of the data
    # This function should return low-dimensional summary statistics S(data)
    # For univariate alpha-stable models, use quantile-based estimators along with the mean of the data
    v_alpha, v_beta, v_gamma = compute_quantiles(data)
    mean_x = np.mean(data)
    return np.array([v_alpha, v_beta, v_gamma, mean_x])

In [8]:
def psi(y, x, covariance = np.diag([0.25,0.25,1,1])):
    # Define smoothing kernel using a Gaussian kernel with estimated covariance
    return multivariate_normal.pdf(y, mean=x, cov=covariance)


In [ ]:
def pi_LF(theta,y) :
    """give the approximate density pi_LF

    Args:
        theta (_type_): _description_
        y (_type_): _description_
    """
    [K((summary_statistics(y)-summary_statistics(x_i))/epsilon)/epsilon for x_i in x]
    

In [9]:
def sigma_hat(theta_hat,n_draws = 1000):
    x = np.array([univ_alpha_stable_sampler(params = theta_hat, size = 200, seed=None) for _ in range(n_draws)])
    sumary_statistics = np.array([S(x_i) for x_i in x])

    return np.cov(sumary_statistics, rowvar=False)

In [10]:
def norm2(u) :
    return np.sqrt(np.sum(u*u))


In [11]:
def K(u, sigma) :
    d = sigma.shape[0]
    #print(d)
    return np.exp(-(u.T@np.linalg.inv(sigma)@u)/2)/(np.sqrt(2*np.pi)**d*np.sqrt(np.linalg.det(sigma)))




In [13]:
def resample(theta, weights,N) :
    normalized_weights = weigths/np.sum(weights)
    theta['t'] = np.random.choice(theta['t-1'], size=N, replace=True, p=normalized_weights)
    weights['t'] = np.ones(N)/N

In [14]:
def sample_from_M_t(N, theta_prev, weights_prev):

    samples = np.zeros((N, 4))
    normalized_weights = weights_prev/np.sum(weights_prev)
    for i in range(N):
        # Choose a component based on the weights
        component = np.random.choice(range(N), p=normalized_weights)
        # Generate a sample from the chosen component
        sample = np.random.multivariate_normal(mean = theta_prev[component], cov = np.diag([0.25,0.25,1,1]))
        samples[i] = sample
        
    return samples  

In [15]:
def M_t(N,theta_i,theta_prev, weights_prev) :
    densities = np.array([ psi(theta_i, theta_prev[i]) for i in range(N)])
    return np.sum(weights_prev*densities)
    

In [110]:
def SMC_sampler(T=10,N =1000,n=200,covariance = np.diag([0.25, 0.25, 1, 1]), seed=42) :
    epsilons = [k for k in range(1000,100, -100)]+[k for k in range(100,9, -1)] + [k+0.5 for k in range(9,4,-1)] + [5-k*0.05 for k in range(40)]+[3-0.01*k for k in range(301)]  # Tolerance schedule
    y = levy_stable.rvs(1.7, 0.9, loc=10, scale=10, size=200)
    ###--------Initialization :
    epsilon = epsilons[0]
    # 1 - sample theta from the prior : 
    # theta is a Nx4 matrix containing all the N theta_i
    initial_theta = np.array([prior_sample(seed) for _ in range(N)])
    theta = {"t" : initial_theta , "t-1" :initial_theta }
    # set weights their initial values :
    x = np.array([univ_alpha_stable_sampler(params=theta['t'][i], size=n, seed=seed) for i in range(N)])
    print('x.shape = ',x.shape)
    initial_weights = np.array([K((S(y)-S(x))/epsilon,sigma_hat(theta_hat))/epsilon for theta_hat in theta['t']])
    print("weights = ", initial_weights)
    print(" sum(weights) = ", np.sum(initial_weights))
    weights = {"t" : initial_weights, "t-1" : initial_weights}
    t=1
    while t<T :
        epsilon = epsilons[t]
        i = 1
        while i<N : 
            # Mutation and correction : 
            theta_maj = theta['t']
            weights_maj = weights['t']
            theta['t'] = sample_from_M_t(N, theta['t-1'], weights['t-1'])
            weights['t'] = np.array([K((S(y)-S(x))/epsilon,sigma_hat(theta_hat))/epsilon for theta_hat in theta['t']])/np.array([M_t(theta['t'][i],theta['t-1'],weights['t-1']) for i in range(N)])
            theta['t-1'] = theta_maj
            weights['t-1'] = weights_maj
            u = np.random.uniform(low=0, high=1, size=N)
            c_t = np.quantile(weights['t'], 0.9)
            proba = 1-np.minimum(1,weights['t']/c_t)
            rejected = theta['t'][u<=proba]
            accepted = theta['t'][u>proba]
            print("accepted = " ,accepted)
            print("acceptance pourcentage = ", len(accepted)*100/N)
            print("rejected = " ,rejected)
            print("rejected pourcentage = ", len(rejected)*100/N) 
            if proba<u : 
                continue
            else : 
                i+=1
                continue 
        # Resample : 
        resample(theta,weights,N)
        print("theta = ", theta)
        print("weights = ", weights)



    






In [16]:
def SMC_sampler_v2(arg, T=10,N =1000,n=200,covariance = np.diag([0.25, 0.25, 1, 1]), seed=42) :
    #epsilons = [k for k in range(1000,100, -100)]+[k for k in range(100,9, -1)] + [k+0.5 for k in range(9,4,-1)] + [5-k*0.05 for k in range(40)]+[3-0.01*k for k in range(301)]  # Tolerance schedule
    epsilons = [3-0.01*k for k in range(301)]
    T = len(epsilons)

    #y = levy_stable.rvs(1.7, 0.9, loc=10, scale=10, size=200)
    ###--------Initialization :
    epsilon = epsilons[0]
    # 1 - sample theta from the prior : 
    # theta is a Nx4 matrix containing all the N theta_i
    #initial_theta = np.array([prior_sample(seed) for _ in range(N)])
    #theta = {"t" : initial_theta , "t-1" :initial_theta }
    # set weights their initial values :
    #x = np.array([univ_alpha_stable_sampler(params=theta['t'][i], size=n, seed=seed) for i in range(N)])
    #print('x.shape = ',x.shape)
    #initial_weights = np.array([K((S(y)-S(x))/epsilon,sigma_hat(theta_hat))/epsilon for theta_hat in theta['t']])
    #print("weights = ", initial_weights)
    #print(" sum(weights) = ", np.sum(initial_weights))
    #weights = {"t" : initial_weights, "t-1" : initial_weights}
    y,x,theta,weights = arg
    t=1
    res = []
    print("INITIALIZATION IS DONE :)")
    while t<T :
        print("t = ",t)
        epsilon = epsilons[t]
        print("epsilon = ",epsilon)
        accepted = []
        rejected = []
        while len(accepted)<N : 
            # Mutation and correction : 
            theta_maj = theta['t']
            weights_maj = weights['t']
            theta['t'] = sample_from_M_t(N, theta['t-1'], weights['t-1'])
            print('theta t = ', theta['t'][:5])
            weights['t'] = np.array([K((S(y)-S(x))/epsilon,sigma_hat(theta_hat))/epsilon for theta_hat in theta['t']])/np.array([M_t(N,theta['t'][i],theta['t-1'],weights['t-1']) for i in range(N)])
            print('weights t = ', weights['t'][:5])
            theta['t-1'] = theta_maj
            weights['t-1'] = weights_maj
            u = np.random.uniform(low=0, high=1, size=N)
            c_t = np.quantile(weights['t'], 0.9)
            proba = 1-np.minimum(1,weights['t']/c_t)
            print('proba = ', proba[:10])
            rejected = theta['t'][u<=proba]
            accepted = theta['t'][u>proba]
            print("accepted = " ,accepted)
            print("acceptance pourcentage = ", len(accepted)*100/N)
            print("rejected = " ,rejected)
            print("rejected pourcentage = ", len(rejected)*100/N)
        t+=1
        res.append((theta['t'], weights['t']))
        # Resample : 
        resample(theta,weights,N)
        print("theta = ", theta)
        print("weights = ", weights)


In [17]:
def initialization(T=10,N =1000,n=200,covariance = np.diag([0.25, 0.25, 1, 1]), seed=42) :
    #epsilons = [k for k in range(1000,100, -100)]+[k for k in range(100,9, -1)] + [k+0.5 for k in range(9,4,-1)] + [5-k*0.05 for k in range(40)]+[3-0.01*k for k in range(301)]  # Tolerance schedule
    epsilons = [3-0.01*k for k in range(301)]
    T = len(epsilons)
    y = levy_stable.rvs(1.7, 0.9, loc=10, scale=10, size=200)
    ###--------Initialization :
    epsilon = epsilons[0]
    # 1 - sample theta from the prior : 
    # theta is a Nx4 matrix containing all the N theta_i
    initial_theta = np.array([prior_sample(seed) for _ in range(N)])
    theta = {"t" : initial_theta , "t-1" :initial_theta }
    # set weights their initial values :
    x = np.array([univ_alpha_stable_sampler(params=theta['t'][i], size=n, seed=seed) for i in range(N)])
    print('x.shape = ',x.shape)
    initial_weights = np.array([K((S(y)-S(x))/epsilon,sigma_hat(theta_hat))/epsilon for theta_hat in theta['t']])
    print("weights = ", initial_weights)
    print(" sum(weights) = ", np.sum(initial_weights))
    weights = {"t" : initial_weights, "t-1" : initial_weights}

    return y,x,theta, weights

In [18]:
arg = initialization()

x.shape =  (1000, 200)
weights =  [2.35490511e-08 5.68842396e-08 2.67831617e-08 1.77735181e-07
 1.21739078e-07 7.33486019e-08 5.97263906e-08 7.09789488e-08
 2.69364484e-08 2.55008662e-08 7.84928589e-08 4.99322764e-08
 4.42754901e-08 6.88781129e-08 7.01224548e-08 8.04409593e-08
 6.61608618e-08 3.86890146e-08 1.18017988e-07 1.43353913e-08
 4.72239717e-08 4.33292685e-08 4.61181420e-08 5.09205926e-08
 6.70159537e-08 1.27712801e-07 1.57224420e-08 8.89674487e-08
 3.93214328e-08 6.36003264e-08 8.49587706e-09 4.94144924e-08
 4.44485695e-08 9.27499643e-08 8.12252007e-08 2.93527351e-08
 4.41520757e-08 4.70682214e-08 3.70190784e-08 2.57305399e-09
 4.32439897e-08 4.77152432e-08 1.76003214e-08 6.02899095e-08
 7.71411325e-08 4.91258158e-08 4.77857427e-08 3.96055558e-08
 6.13716392e-08 3.92350787e-08 5.14721357e-08 3.51243262e-08
 2.67471950e-08 1.90313399e-08 7.21203931e-08 1.27796500e-08
 4.42067352e-08 7.74713562e-08 4.62575037e-08 5.13500880e-08
 3.21627357e-08 1.05882326e-07 3.11227445e-08 2.707

In [126]:
SMC_sampler_v2(arg=arg)

INITIALIZATION IS DONE :)
t =  1
epsilon =  2.99
theta t =  [[ 2.78905613e+00  2.16600463e-01  2.18363069e+02 -1.18309661e+02]
 [ 1.68342570e+00  2.63642709e-01  2.20826609e+02 -1.23199855e+02]
 [ 1.99786840e+00  6.73575848e-01  2.18739438e+02 -1.20074706e+02]
 [ 2.04688650e+00 -9.31527663e-01  2.19726049e+02 -1.20214134e+02]
 [ 1.92731057e+00 -6.38246148e-02  2.19631342e+02 -1.19577946e+02]]


/tmp/ipykernel_242028/1118787516.py:15: RuntimeWarning: invalid value encountered in power
  y_bar = (S*(np.sin(alpha)*(u+B))*(np.cos(u-alpha*(u+B))/w)**((1-alpha)/alpha))/np.cos(u)**(1/alpha)
/opt/mamba/lib/python3.11/site-packages/numpy/linalg/linalg.py:2180: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


weights t =  [           nan 1.16218282e-01 2.54619340e-12            nan
 1.81007260e-03]
proba =  [nan nan nan nan nan nan nan nan nan nan]
accepted =  []
acceptance pourcentage =  0.0
rejected =  []
rejected pourcentage =  0.0
theta t =  [[ 1.57592293e+00 -8.15447053e-01  2.20285173e+02 -1.19767615e+02]
 [ 2.10750423e+00  2.20849298e-01  2.16087235e+02 -1.19836387e+02]
 [ 1.88971939e+00  8.57714899e-01  2.20387740e+02 -1.22052045e+02]
 [ 2.35224770e+00  2.37089074e-01  2.20527400e+02 -1.19564615e+02]
 [ 2.17407454e+00  2.14456715e-01  2.19064634e+02 -1.21302130e+02]]


/tmp/ipykernel_242028/538432180.py:4: RuntimeWarning: overflow encountered in scalar power
  return np.exp(-u.T@np.linalg.inv(sigma)@u/2)/(np.sqrt(2*np.pi*np.linalg.det(sigma)**2))**d
/tmp/ipykernel_242028/1118787516.py:15: RuntimeWarning: overflow encountered in power
  y_bar = (S*(np.sin(alpha)*(u+B))*(np.cos(u-alpha*(u+B))/w)**((1-alpha)/alpha))/np.cos(u)**(1/alpha)
/tmp/ipykernel_242028/1151381473.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  v_alpha = (quantiles[4] - quantiles[0]) / (quantiles[3] - quantiles[1])
/opt/mamba/lib/python3.11/site-packages/numpy/core/_methods.py:118: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)


weights t =  [4.32037823e-23            nan 1.48973528e-05            nan
            nan]
proba =  [nan nan nan nan nan nan nan nan nan nan]
accepted =  []
acceptance pourcentage =  0.0
rejected =  []
rejected pourcentage =  0.0


ValueError: probabilities contain NaN

In [14]:
test = {'t' : [1,23,34]}
test['t'][1]

23

In [7]:
[prior_sample(42) for _ in range(2)]

[[1.849080237694725,
  -0.049285693590083834,
  219.59818254342153,
  -120.40245474088903],
 [1.849080237694725,
  -0.049285693590083834,
  219.59818254342153,
  -120.40245474088903]]

In [10]:
liste = np.array([prior_sample(42) for _ in range(2)])
liste

array([[ 1.84908024e+00, -4.92856936e-02,  2.19598183e+02,
        -1.20402455e+02],
       [ 1.84908024e+00, -4.92856936e-02,  2.19598183e+02,
        -1.20402455e+02]])

In [11]:
liste.shape

(2, 4)