In [1]:
import numpy as np
from scipy.stats import levy_stable
from scipy.stats import uniform
from scipy.stats import multivariate_normal

In [2]:
def prior_sample():
    # Sample from prior distribution
    # For univariate alpha-stable models, sample each parameter from its respective uniform distribution
    #np.random.seed(seed)
    alpha = uniform.rvs(1.1, 0.9)  # U[1.1, 2]
    beta = uniform.rvs(-1, 2)  # U[-1, 1]
    gamma = uniform.rvs(0, 300)  # U[0, 300]
    delta = uniform.rvs(-300, 600)  # U[-300, 300]
    return [alpha, beta, gamma, delta]

In [3]:
def univ_alpha_stable_sampler(params,size,seed) :
    alpha,beta,gamma,delta = params[0],params[1],params[2],params[3]
    #print(alpha,beta,gamma,delta)
    y_bar = 0
    np.random.seed(seed)
    w = np.random.standard_exponential(size=size)
    u = np.random.uniform(low = -np.pi/2, high = np.pi/2, size = size)
    if alpha == 1 :
        y_bar = 2/np.pi*((np.pi/2+beta*u)*np.tan(u)-beta*np.log((np.pi/2*w*np.cos(u))/(np.pi/2+beta*u)))
        return gamma*y_bar + delta
    else :
        S = (1+beta**2*np.tan(np.pi*alpha/2)**2)**(1/(2*alpha))
        B = 1/alpha*np.arctan(beta*np.tan(np.pi*alpha/2))
        #print(S,B)
        y_bar = (S*(np.sin(alpha)*(u+B))*(np.cos(u-alpha*(u+B))/w)**((1-alpha)/alpha))/np.cos(u)**(1/alpha)
        return gamma*y_bar + delta

In [4]:
def compute_quantiles(data):
    # Compute quantile-based summary statistics
    quantiles = np.percentile(data, [5, 25, 50, 75, 95])
    v_alpha = (quantiles[4] - quantiles[0]) / (quantiles[3] - quantiles[1])
    v_beta = (quantiles[4] + quantiles[0] - 2 * quantiles[2]) / (quantiles[4] - quantiles[0])
    v_gamma = (quantiles[3] - quantiles[1]) / quantiles[2]
    return v_alpha, v_beta, v_gamma

In [5]:
def S(data):
    # Compute summary statistics of the data
    # This function should return low-dimensional summary statistics S(data)
    # For univariate alpha-stable models, use quantile-based estimators along with the mean of the data
    v_alpha, v_beta, v_gamma = compute_quantiles(data)
    mean_x = np.mean(data)
    return np.array([v_alpha, v_beta, v_gamma, mean_x])

In [6]:
def psi(y, x, covariance = np.diag([0.25,0.25,1,1])):
    # Define smoothing kernel using a Gaussian kernel with estimated covariance
    return multivariate_normal.pdf(y, mean=x, cov=covariance)


In [7]:
def cov_estimate(theta_hat,n_draws = 1000):
    x = np.array([univ_alpha_stable_sampler(params = theta_hat, size = 200, seed=None) for _ in range(n_draws)])
    sumary_statistics = np.array([S(x_i) for x_i in x])

    return np.cov(sumary_statistics, rowvar=False)

In [8]:
def norm2(u) :
    return np.sqrt(np.sum(u*u))


In [9]:
def K(u, sigma) :
    d = sigma.shape[0]
    #print(d)
    return np.exp(-(u.T@np.linalg.inv(sigma)@u)/2)/(np.sqrt(2*np.pi)**d*np.sqrt(np.linalg.det(sigma)))




In [10]:
def resample(theta, weights,N) :
    normalized_weights = weigths/np.sum(weights)
    theta['t'] = np.random.choice(theta['t-1'], size=N, replace=True, p=normalized_weights)
    weights['t'] = np.ones(N)/N

In [11]:
def sample_from_M_t(N, theta_prev, weights_prev):
    normalized_weights = weights_prev/np.sum(weights_prev)
    # Choose a component based on the weights
    component = np.random.choice(range(N), p=normalized_weights)
    # Generate a sample from the chosen component
    sample = np.random.multivariate_normal(mean = theta_prev[component], cov = np.diag([0.25,0.25,1,1]))
    #samples[i] = sample
    return sample 

In [12]:
def M_t(N,theta_i,theta_prev, weights_prev) :
    densities = np.array([ psi(theta_i, theta_prev[i]) for i in range(N)])
    return np.sum(weights_prev*densities)
    

In [13]:
def normalize(u) :
    return u/np.sum(u)


In [83]:
def SMC_sampler_v2(arg, T=10,N =1000,n=200,covariance = np.diag([0.25, 0.25, 1, 1]), seed=42) :
    #epsilons = [k for k in range(1000,100, -100)]+[k for k in range(100,9, -1)] + [k+0.5 for k in range(9,4,-1)] + [5-k*0.05 for k in range(40)]+[3-0.01*k for k in range(301)]  # Tolerance schedule
    epsilons = [100*k for k in range(10,0,-1)]
    T = len(epsilons)

    #y = levy_stable.rvs(1.7, 0.9, loc=10, scale=10, size=200)
    ###--------Initialization :
    epsilon = epsilons[0]
    # 1 - sample theta from the prior : 
    # theta is a Nx4 matrix containing all the N theta_i
    #initial_theta = np.array([prior_sample(seed) for _ in range(N)])
    #theta = {"t" : initial_theta , "t-1" :initial_theta }
    # set weights their initial values :
    #x = np.array([univ_alpha_stable_sampler(params=theta['t'][i], size=n, seed=seed) for i in range(N)])
    #print('x.shape = ',x.shape)
    #initial_weights = np.array([K((S(y)-S(x))/epsilon,sigma_hat(theta_hat))/epsilon for theta_hat in theta['t']])
    #print("weights = ", initial_weights)
    #print(" sum(weights) = ", np.sum(initial_weights))
    #weights = {"t" : initial_weights, "t-1" : initial_weights}
    y,x,theta,weights,sigma_hat = arg
    t=1
    res = []
    sigma_hat = np.diag([0.25,0.25,1,1])
    print("INITIALIZATION IS DONE :)")
    while t<T :
        print("t = ",t)
        epsilon = epsilons[t]
        print("epsilon = ",epsilon)
        accepted = []
        rejected = []
        theta_maj = theta['t']
        weights_maj = weights['t']
        i = 0 
        
        while i<N : 
            print('###########    i = ',i)
            """
            weights['t'] = normalize(weights['t'])
            weights['t-1'] = normalize(weights['t-1'])
            """
            c_t = np.quantile(weights['t'], 0.9)
            # Mutation and correction : 
            theta['t'][i] = sample_from_M_t(N, theta['t-1'], weights['t-1'])
            print(f'theta["t"][{i}]= ', np.round(theta['t'][i],3))
            #sigma_hat = cov_estimate(np.array([1.7,0.9,10,10]))
            weights['t'][i] = (K((S(y)-S(x[i]))/epsilon,sigma_hat)/epsilon)/M_t(N,theta['t'][i],theta['t-1'],weights['t-1'])
            """
            weights['t'] = normalize(weights['t'])
            weights['t-1'] = normalize(weights['t-1'])
            """
            print('weights["t"] = ', np.round(weights['t'][:5],3))
            #theta['t-1'] = theta_maj
            #weights['t-1'] = weights_maj
            u = np.random.uniform(low=0, high=1, size=1)
            #c_t = np.quantile(weights['t'], 0.9)
            proba = 1-np.minimum(1,weights['t']/c_t)
            print("c_t = ", c_t)
            print(f"weights['t'][{i}]/c_t = ", weights['t'][i]/c_t)
            print(f'proba[{i}] = ', proba[i])
            if u<=proba[i] :
                #Rejection : 
                print(f"theta['t'][{i}] = {np.round(theta['t'][i],3)} rejected !")
                continue
            else : 
                # Acceptance
                print(f"theta['t'][{i}] = {np.round(theta['t'][i],3)} accepted !")
                weights['t'][i] = weights['t'][i]/(1-proba[i])
                i = i+1
            """
            rejected = theta['t'][u<=proba]
            accepted = theta['t'][u>proba]
            
            print("accepted = ",accepted)
            print("acceptance pourcentage = ", len(accepted)*100/N)
            print("rejected = " ,rejected)
            print("rejected pourcentage = ", len(rejected)*100/N)
            """
        t+=1
        theta['t-1'],weights['t-1'] = theta_maj,weights_maj
        res.append((theta['t'], weights['t']))
        # Resample : 
        resample(theta,weights,N)
        print("theta = ", theta[:5])
        print("weights = ", weights[:5])


In [49]:
def initialization(T=10,N =1000,n=200,covariance = np.diag([0.25, 0.25, 1, 1]), seed=42) :
    #epsilons = [k for k in range(1000,100, -100)]+[k for k in range(100,9, -1)] + [k+0.5 for k in range(9,4,-1)] + [5-k*0.05 for k in range(40)]+[3-0.01*k for k in range(301)]  # Tolerance schedule
    epsilons = [100*k for k in range(10,0,-1)]
    T = len(epsilons)
    y = levy_stable.rvs(1.7, 0.9, loc=10, scale=10, size=200)
    ###--------Initialization :
    epsilon = epsilons[0]

    sigma_hat = cov_estimate(np.array([1.7,0.9,10,10]))
    print("sigma_hat = ", sigma_hat)
    print('det(sigma_hat) = ', np.linalg.det(sigma_hat))
    # 1 - sample theta from the prior : 
    # theta is a Nx4 matrix containing all the N theta_i
    initial_theta = np.array([prior_sample() for _ in range(N)])
    theta = {"t" : initial_theta , "t-1" :initial_theta }
    print('theta["t"] = ',np.round(theta['t'][:5],4))
    # set weights their initial values :
    x = np.array([univ_alpha_stable_sampler(params=theta['t'][i], size=n, seed=seed) for i in range(N)])
    print('x.shape = ',x.shape)
    initial_weights = np.array([K((S(y)-S(x[i]))/epsilon,sigma_hat)/epsilon for i in range(N)])
    print("weights = ", initial_weights)

    #print(" sum(weights) = ", np.sum(normalize(initial_weights)))

    #weights = {"t" : normalize(initial_weights), "t-1" : normalize(initial_weights)}
    weights = {"t" : normalize(initial_weights), "t-1" : normalize(initial_weights)}
    return y,x,theta,weights,sigma_hat

In [50]:
arg = initialization()

sigma_hat =  [[ 2.69605321e+00 -1.10040600e-01 -9.16950249e-02 -6.39348574e+00]
 [-1.10040600e-01  2.16679577e-02 -2.33848468e-02  8.23158569e-01]
 [-9.16950249e-02 -2.33848468e-02  2.81029125e-01 -1.73279261e+00]
 [-6.39348574e+00  8.23158569e-01 -1.73279261e+00  3.59719629e+02]]
det(sigma_hat) =  3.498195190840059
theta["t"] =  [[   1.8582    0.7118  137.0815   -4.6453]
 [   1.9807    0.6456  162.1432  190.9923]
 [   1.8044    0.5724  189.6659 -257.5192]
 [   1.5647   -0.546    51.2432 -272.5375]
 [   1.8001   -0.8204  251.2753  245.0883]]
x.shape =  (1000, 200)
weights =  [1.31101276e-05 1.35428365e-05 1.35386873e-05 1.35414029e-05
 1.35403930e-05 1.35381309e-05 1.35137804e-05 1.35285676e-05
 1.35422204e-05 1.35422945e-05 1.35409131e-05 1.35418754e-05
 1.35410276e-05 1.35427962e-05 1.35319398e-05 1.35418899e-05
 1.35414478e-05 1.35423550e-05 1.35421452e-05 1.35354960e-05
 1.35382471e-05 1.35294590e-05 1.35423398e-05 1.35416904e-05
 1.35141129e-05 1.35428449e-05 1.35383093e-05 1.3542

In [54]:
SMC_sampler_v2(arg=arg)

INITIALIZATION IS DONE :)
t =  1
epsilon =  900
###########    i =  0
theta["t"][0]=  [  1.838   0.61  180.107 163.653]
weights["t"] =  [1.002 0.142 0.142 0.142 0.142]
c_t =  0.141665386994538
weights['t'][0]/c_t =  7.0755795155355266
proba[0] =  0.0
theta['t'][0] = [  1.838   0.61  180.107 163.653] accepted !
###########    i =  1
theta["t"][1]=  [  1.221   0.443 259.258  46.897]
weights["t"] =  [1.002 0.946 0.142 0.142 0.142]
c_t =  0.141665386994538
weights['t'][1]/c_t =  6.675621934909214
proba[1] =  0.0
theta['t'][1] = [  1.221   0.443 259.258  46.897] accepted !
###########    i =  2
theta["t"][2]=  [  2.55    0.504  51.607 -41.404]
weights["t"] =  [1.002 0.946 0.933 0.142 0.142]
c_t =  0.14166538699453843
weights['t'][2]/c_t =  6.58741682241227
proba[2] =  0.0
theta['t'][2] = [  2.55    0.504  51.607 -41.404] accepted !
###########    i =  3
theta["t"][3]=  [ -0.978  -1.167 120.098  29.949]
weights["t"] =  [1.002 0.946 0.933 1.033 0.142]
c_t =  0.14166538699454934
weights['t'][3

KeyboardInterrupt: 